version: '3'

services:

  #本番ではDBはRDSをつかうのでこちらはオフ！
  db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./src/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-network

  app: #rubyね
    build:
      context: .
# =========ローカルと本番切り替え===========
    #command: bundle exec puma -C config/puma.rb -e production
    command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - ./src:/app
      - public-data:/app/public
      - tmp-data:/app/tmp
      - log-data:/app/log
    networks:
      - app-network
    #本番環境ではオフ！
    depends_on:
      - db

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  app-network:
    external: true
