version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2


jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.3
    working_directory: ~/BP/src
    steps:
      - checkout:
          path: ~/BP
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7.3
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: tester
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: ~/BP/src
    steps:
      - checkout:
          path: ~/BP
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:create db:migrate
      #- run:
      #    name: tester
      #    command: bundle exec rake test
      
      #- run:
      #    name: rspec
      #    command: bundle exec rspec
      - ruby/rspec-test

  deploy:
    machine:
      image: ubuntu-2004:202104-01
    steps:
      - checkout
            # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys
            # CircleCI に登録した環境変数を使って SSH
      - run: ssh ec2-user@54.168.110.37 'cd /BP && sudo git fetch && sudo git merge origin/main'

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: main
